### ISSUE TITLE
docker compose quickstart: http://localhost:8888/secured does not allow the "Create a passkey" button to be pressed.

### ISSUE THREAD

**Issue by gedw99** [teamhanko/hanko#279] opened 2022-10-11 09:31 UTC
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

am trying the quick start  and have it running with docker compose,. I signed up with my email ( and got the 2fa key via mailslurper gui )  but the redirect to  the screen at http://localhost:8888/secured does not allow the "Create a passkey" button to be pressed.

### Reproducing the bug

In deploy folder:
docker-compose -f deploy/docker-compose/quickstart.yaml -p "hanko-quickstart" up --build

go to http://localhost:8888 and signup with email.

goto http://localhost:8080/ and copy the 6 digit 2fa into the GUI.

it auths the 2fs and redirects me to http://localhost:8888/secured where the "Create a Passkey" button is not able to be pressed. 

### Logs

```Shell
*  Executing task: docker logs --tail 1000 -f 75fac641c1718deb6dd080e52fb0415f950429740fa8f4b6e39613f590f7057d 

export PATH=/usr/local/opt/go/libexec/bin:$PATH
clear
2022/10/11 08:48:24 Using config file: /etc/config/config.yaml
⇨ http server started on [::]:8001
⇨ http server started on [::]:8000
{"time":"2022-10-11T08:56:46.102537Z","time_unix":"1665478606","id":"U2lX6KSbaBH1AdFfh0FsJNZBTJxWZnCZ","remote_ip":"172.18.0.1","host":"localhost:8000","method":"OPTIONS","uri":"/.well-known/config","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":204,"error":"","latency":1852000,"latency_human":"1.852ms","bytes_in":0,"bytes_out":0,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T08:56:46.151752Z","time_unix":"1665478606","id":"XUPS31pD3Mu1mM6LcjZ9sStfeyxZnlbn","remote_ip":"172.18.0.1","host":"localhost:8000","method":"GET","uri":"/.well-known/config","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":200,"error":"","latency":5890000,"latency_human":"5.89ms","bytes_in":0,"bytes_out":55,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T08:56:46.299488Z","time_unix":"1665478606","id":"0etz6dDXYkgeicjxx8iGFAIUWPStbawi","remote_ip":"172.18.0.1","host":"localhost:8000","method":"OPTIONS","uri":"/me","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":204,"error":"","latency":76000,"latency_human":"76µs","bytes_in":0,"bytes_out":0,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T08:56:46.362332Z","time_unix":"1665478606","id":"C8tu1QJu3VaMEbzd9kTov9yVgVyPCWxn","remote_ip":"172.18.0.1","host":"localhost:8000","method":"GET","uri":"/me","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":400,"error":"code=400, message=missing or malformed jwt","latency":13753000,"latency_human":"13.753ms","bytes_in":0,"bytes_out":50,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:10:24.836431Z","time_unix":"1665479424","id":"dogi1WeI9srE0YhF4et8QqUomFYs6Z7T","remote_ip":"172.18.0.1","host":"localhost:8000","method":"OPTIONS","uri":"/.well-known/config","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":204,"error":"","latency":280000,"latency_human":"280µs","bytes_in":0,"bytes_out":0,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:10:24.845709Z","time_unix":"1665479424","id":"D5TDdHGgRa030Fqih5fbLF80w48ur7wP","remote_ip":"172.18.0.1","host":"localhost:8000","method":"GET","uri":"/.well-known/config","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":200,"error":"","latency":74000,"latency_human":"74µs","bytes_in":0,"bytes_out":55,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:10:25.09264Z","time_unix":"1665479425","id":"uiz0ZGSgtwMoQJvfHPg3yK28NBK93sYP","remote_ip":"172.18.0.1","host":"localhost:8000","method":"OPTIONS","uri":"/me","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":204,"error":"","latency":70000,"latency_human":"70µs","bytes_in":0,"bytes_out":0,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:10:25.224483Z","time_unix":"1665479425","id":"SSvVDRorAdUSMacE0Vf6G5oTrJRof9mz","remote_ip":"172.18.0.1","host":"localhost:8000","method":"GET","uri":"/me","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":400,"error":"code=400, message=missing or malformed jwt","latency":116000,"latency_human":"116µs","bytes_in":0,"bytes_out":50,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:11:18.018275Z","time_unix":"1665479478","id":"VpD5Mis2fbotPTWnWS3y8lgljjmKbbOt","remote_ip":"172.18.0.1","host":"localhost:8000","method":"OPTIONS","uri":"/user","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":204,"error":"","latency":402000,"latency_human":"402µs","bytes_in":0,"bytes_out":0,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:11:18.074268Z","time_unix":"1665479478","id":"ZsAbyEOAjvejH6OKKSd3lfTkb6uwoWVf","remote_ip":"172.18.0.1","host":"localhost:8000","method":"POST","uri":"/user","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":404,"error":"Not Found: user not found","latency":26018000,"latency_human":"26.018ms","bytes_in":28,"bytes_out":35,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:11:23.448162Z","time_unix":"1665479483","id":"M8sDj8B9ai7Y6rlkMUMjZ5IrYei53TNb","remote_ip":"172.18.0.1","host":"localhost:8000","method":"OPTIONS","uri":"/users","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":204,"error":"","latency":51000,"latency_human":"51µs","bytes_in":0,"bytes_out":0,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:11:23.472835Z","time_unix":"1665479483","id":"DiuVodzSUtN7Y3ZooAl40ksvBYTnGAJc","remote_ip":"172.18.0.1","host":"localhost:8000","method":"POST","uri":"/users","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":200,"error":"","latency":19230000,"latency_human":"19.23ms","bytes_in":28,"bytes_out":176,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:11:23.507473Z","time_unix":"1665479483","id":"skQBeRfDPdthHe2boQ5A0LQNDsrY43C4","remote_ip":"172.18.0.1","host":"localhost:8000","method":"OPTIONS","uri":"/passcode/login/initialize","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":204,"error":"","latency":135000,"latency_human":"135µs","bytes_in":0,"bytes_out":0,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:11:23.930303Z","time_unix":"1665479483","id":"XkGKT0XelnNSdACDjiJlriVULZJ3QAef","remote_ip":"172.18.0.1","host":"localhost:8000","method":"POST","uri":"/passcode/login/initialize","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":200,"error":"","latency":407220000,"latency_human":"407.22ms","bytes_in":50,"bytes_out":99,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:11:55.045389Z","time_unix":"1665479515","id":"T4hK2f51uU0QY5hPH3kqwtJR0M77zaCU","remote_ip":"172.18.0.1","host":"localhost:8000","method":"OPTIONS","uri":"/passcode/login/finalize","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":204,"error":"","latency":54000,"latency_human":"54µs","bytes_in":0,"bytes_out":0,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:11:55.499244Z","time_unix":"1665479515","id":"EDmuGxVRuocyyyvZgUSiedaCF7U8QJLw","remote_ip":"172.18.0.1","host":"localhost:8000","method":"POST","uri":"/passcode/login/finalize","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":200,"error":"","latency":446992000,"latency_human":"446.992ms","bytes_in":61,"bytes_out":99,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:11:55.513373Z","time_unix":"1665479515","id":"WmIgTr8DSwQFCysbbhCKP0J7B41WIHzm","remote_ip":"172.18.0.1","host":"localhost:8000","method":"OPTIONS","uri":"/me","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":204,"error":"","latency":85000,"latency_human":"85µs","bytes_in":0,"bytes_out":0,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:11:55.520832Z","time_unix":"1665479515","id":"rPziGyb81yQbIR8GSEMahZpb7w2A3jt1","remote_ip":"172.18.0.1","host":"localhost:8000","method":"GET","uri":"/me","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":200,"error":"","latency":1265000,"latency_human":"1.265ms","bytes_in":0,"bytes_out":46,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:11:55.532044Z","time_unix":"1665479515","id":"tLOuQbKOhlP0eDB3kTYgMfP9VqkypxUx","remote_ip":"172.18.0.1","host":"localhost:8000","method":"OPTIONS","uri":"/users/b208dbba-84a7-43cf-a3ad-3e0f4edd21a2","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":204,"error":"","latency":75000,"latency_human":"75µs","bytes_in":0,"bytes_out":0,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:11:55.543142Z","time_unix":"1665479515","id":"rAtjWisXVaQ8qmJAQviDWAbHFekSKo8v","remote_ip":"172.18.0.1","host":"localhost:8000","method":"GET","uri":"/users/b208dbba-84a7-43cf-a3ad-3e0f4edd21a2","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":200,"error":"","latency":5252000,"latency_human":"5.252ms","bytes_in":0,"bytes_out":175,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:11:56.112497Z","time_unix":"1665479516","id":"SevXnlznP5r4Dl3cjSau9nL0g8M8uMOC","remote_ip":"172.18.0.6","host":"hanko:8000","method":"GET","uri":"/.well-known/jwks.json","user_agent":"Go-http-client/1.1","status":200,"error":"","latency":4519000,"latency_human":"4.519ms","bytes_in":0,"bytes_out":797,"referer":""}
{"time":"2022-10-11T09:11:56.419236Z","time_unix":"1665479516","id":"VMY5Fj0thQBzriAcVpGSnMewM6f6B4Ao","remote_ip":"172.18.0.1","host":"localhost:8000","method":"GET","uri":"/me","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":200,"error":"","latency":5343000,"latency_human":"5.343ms","bytes_in":0,"bytes_out":46,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:11:56.557699Z","time_unix":"1665479516","id":"TZZubTimPdckt16qzpg0NBQh1WED3QLv","remote_ip":"172.18.0.1","host":"localhost:8000","method":"GET","uri":"/users/b208dbba-84a7-43cf-a3ad-3e0f4edd21a2","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":200,"error":"","latency":11335000,"latency_human":"11.335ms","bytes_in":0,"bytes_out":175,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:12:19.383571Z","time_unix":"1665479539","id":"hm6C4st8wCVWwMgD4LK6uZahUktvH1ik","remote_ip":"172.18.0.1","host":"localhost:8000","method":"OPTIONS","uri":"/.well-known/config","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":204,"error":"","latency":39000,"latency_human":"39µs","bytes_in":0,"bytes_out":0,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:12:19.401008Z","time_unix":"1665479539","id":"bpZo2ms20xRoyqGREhr8WFl6p9t4MoWh","remote_ip":"172.18.0.1","host":"localhost:8000","method":"GET","uri":"/.well-known/config","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":200,"error":"","latency":62000,"latency_human":"62µs","bytes_in":0,"bytes_out":55,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:12:19.479697Z","time_unix":"1665479539","id":"JsnMq0eNdJ5e1HWVfXZjYTrdzuYgiajt","remote_ip":"172.18.0.1","host":"localhost:8000","method":"OPTIONS","uri":"/me","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":204,"error":"","latency":97000,"latency_human":"97µs","bytes_in":0,"bytes_out":0,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:12:19.490667Z","time_unix":"1665479539","id":"TVN0HZ21tBMMEtwOxzGu57cTu4cthzs6","remote_ip":"172.18.0.1","host":"localhost:8000","method":"GET","uri":"/me","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":400,"error":"code=400, message=missing or malformed jwt","latency":61000,"latency_human":"61µs","bytes_in":0,"bytes_out":50,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:18:12.984728Z","time_unix":"1665479892","id":"qotGQr63kk9yT3FNlpdPKx9Mho1WrFMB","remote_ip":"172.18.0.1","host":"localhost:8000","method":"OPTIONS","uri":"/.well-known/config","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":204,"error":"","latency":150000,"latency_human":"150µs","bytes_in":0,"bytes_out":0,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:18:12.99332Z","time_unix":"1665479892","id":"T6zo55nxiMSycU6bgv9E76ZjR3RCRHbd","remote_ip":"172.18.0.1","host":"localhost:8000","method":"GET","uri":"/.well-known/config","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":200,"error":"","latency":82000,"latency_human":"82µs","bytes_in":0,"bytes_out":55,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:18:13.085154Z","time_unix":"1665479893","id":"fAIbtZDAGcppa6gSlmHgeVDQgajOQmGm","remote_ip":"172.18.0.1","host":"localhost:8000","method":"OPTIONS","uri":"/me","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":204,"error":"","latency":362000,"latency_human":"362µs","bytes_in":0,"bytes_out":0,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:18:13.110946Z","time_unix":"1665479893","id":"p9Ixk7xjtcz4khwliB9HXUr1PNVlCobg","remote_ip":"172.18.0.1","host":"localhost:8000","method":"GET","uri":"/me","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":400,"error":"code=400, message=missing or malformed jwt","latency":235000,"latency_human":"235µs","bytes_in":0,"bytes_out":50,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:19:38.06402Z","time_unix":"1665479978","id":"60BpNIItQYdaxMwbqhcHS9vbhCyOQqb8","remote_ip":"172.18.0.1","host":"localhost:8000","method":"OPTIONS","uri":"/user","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":204,"error":"","latency":150000,"latency_human":"150µs","bytes_in":0,"bytes_out":0,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:19:38.080543Z","time_unix":"1665479978","id":"BEeATG25ue5lpCSGtCWz1ExHBt5JAL12","remote_ip":"172.18.0.1","host":"localhost:8000","method":"POST","uri":"/user","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":200,"error":"","latency":3494000,"latency_human":"3.494ms","bytes_in":28,"bytes_out":94,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:19:38.094206Z","time_unix":"1665479978","id":"yGZEvFr5w5PgbbvHHreWN7iqKa0VgDLR","remote_ip":"172.18.0.1","host":"localhost:8000","method":"OPTIONS","uri":"/passcode/login/initialize","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":204,"error":"","latency":67000,"latency_human":"67µs","bytes_in":0,"bytes_out":0,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:19:38.476614Z","time_unix":"1665479978","id":"zHdE4h5V5niMJ7yv31riQJerDjRVPsOI","remote_ip":"172.18.0.1","host":"localhost:8000","method":"POST","uri":"/passcode/login/initialize","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":200,"error":"","latency":374887000,"latency_human":"374.887ms","bytes_in":50,"bytes_out":99,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:19:54.739095Z","time_unix":"1665479994","id":"0xVRb32uFA9WhPQJdky8yZgzpTy9xIfo","remote_ip":"172.18.0.1","host":"localhost:8000","method":"OPTIONS","uri":"/passcode/login/finalize","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":204,"error":"","latency":73000,"latency_human":"73µs","bytes_in":0,"bytes_out":0,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:19:55.127985Z","time_unix":"1665479995","id":"USFb5dv0Ap79nhLe7fWODcWkjSELPDDp","remote_ip":"172.18.0.1","host":"localhost:8000","method":"POST","uri":"/passcode/login/finalize","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":401,"error":"Unauthorized: passcode invalid","latency":374251000,"latency_human":"374.251ms","bytes_in":61,"bytes_out":38,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:20:06.338548Z","time_unix":"1665480006","id":"uXHX9KyCglvFSA3wvYUy8QQqiQMculNS","remote_ip":"172.18.0.1","host":"localhost:8000","method":"OPTIONS","uri":"/passcode/login/finalize","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":204,"error":"","latency":60000,"latency_human":"60µs","bytes_in":0,"bytes_out":0,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:20:06.742371Z","time_unix":"1665480006","id":"ULVEMsQqwQPsRmWXF4ex362DLu9aaK67","remote_ip":"172.18.0.1","host":"localhost:8000","method":"POST","uri":"/passcode/login/finalize","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":200,"error":"","latency":397889000,"latency_human":"397.889ms","bytes_in":61,"bytes_out":99,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:20:06.753688Z","time_unix":"1665480006","id":"YekM7yw6HYExGAqWcAKQ8orUOFmBOHn6","remote_ip":"172.18.0.1","host":"localhost:8000","method":"OPTIONS","uri":"/me","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":204,"error":"","latency":59000,"latency_human":"59µs","bytes_in":0,"bytes_out":0,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:20:06.760034Z","time_unix":"1665480006","id":"UZqIsKri1foQAwnHOHEpu61HayXpilXA","remote_ip":"172.18.0.1","host":"localhost:8000","method":"GET","uri":"/me","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":200,"error":"","latency":451000,"latency_human":"451µs","bytes_in":0,"bytes_out":46,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:20:06.771208Z","time_unix":"1665480006","id":"opIZq4kVToAy1iZMyeF3miJs0IomEKt5","remote_ip":"172.18.0.1","host":"localhost:8000","method":"OPTIONS","uri":"/users/b208dbba-84a7-43cf-a3ad-3e0f4edd21a2","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":204,"error":"","latency":99000,"latency_human":"99µs","bytes_in":0,"bytes_out":0,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:20:06.779951Z","time_unix":"1665480006","id":"tQE6xUkXomZ487c9DNVMEHxoQh5rZHaK","remote_ip":"172.18.0.1","host":"localhost:8000","method":"GET","uri":"/users/b208dbba-84a7-43cf-a3ad-3e0f4edd21a2","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":200,"error":"","latency":4035000,"latency_human":"4.035ms","bytes_in":0,"bytes_out":175,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:20:07.347806Z","time_unix":"1665480007","id":"fbK83MWMN73N9KhZnjO4rhlqwLAvoZ18","remote_ip":"172.18.0.6","host":"hanko:8000","method":"GET","uri":"/.well-known/jwks.json","user_agent":"Go-http-client/1.1","status":200,"error":"","latency":2353000,"latency_human":"2.353ms","bytes_in":0,"bytes_out":797,"referer":""}
{"time":"2022-10-11T09:20:07.605745Z","time_unix":"1665480007","id":"oWyKe98kxhGJVABt1Vum6ccQLfREIerK","remote_ip":"172.18.0.1","host":"localhost:8000","method":"GET","uri":"/me","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":200,"error":"","latency":2025000,"latency_human":"2.025ms","bytes_in":0,"bytes_out":46,"referer":"http://localhost:8888/"}
{"time":"2022-10-11T09:20:07.72657Z","time_unix":"1665480007","id":"Vdn5L7dneAw3R0WcWS6rS4sePIcpGiZf","remote_ip":"172.18.0.1","host":"localhost:8000","method":"GET","uri":"/users/b208dbba-84a7-43cf-a3ad-3e0f4edd21a2","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15","status":200,"error":"","latency":12150000,"latency_human":"12.15ms","bytes_in":0,"bytes_out":175,"referer":"http://localhost:8888/"}
```

### Configuration

```yml
database:
  user: hanko
  password: hanko
  host: postgresd
  port: 5432
  dialect: postgres
passcode:
  email:
    from_address: no-reply@hanko.io
  smtp:
    host: "mailslurper"
    port: "2500"
secrets:
  keys:
    - abcedfghijklmnopqrstuvwxyz
service:
  name: Hanko Authentication Service
server:
  public:
    cors:
      enabled: true
      allow_credentials: true
      allow_origins:
        - "*"
webauthn:
  relying_party:
    origin: "http://localhost:8888"
session:
  cookie:
    secure: false # is needed for safari, because safari does not store secure cookies on localhost
```

### Hanko Version

b450fb505a35be92f0f2f00da2fb37081f67a2c4

### OS

macOS

### OS Version

Mac OS Big Sur 

### Environment

Docker Compose

**Comment by aspeteRakete** [comment] 2022-10-12 08:22
We forgot to include in the Bug Templates: Which Browser Version have you tried this on?

**Comment by DattaAdsule** [comment] 2022-11-21 17:24
Anyone found solution because I am  facing same issue
https://github.com/teamhanko/hanko/issues/351#issuecomment-1322185806

**Comment by gedw99** [comment] 2022-11-22 19:18
> We forgot to include in the Bug Templates: Which Browser Version have you tried this on?

Safari

**Comment by gedw99** [comment] 2023-01-17 13:26
thanks @FlxMgdnz 

sounds like i should wait and try again when the profile element is introduced ? 

BTW here is he full version info. Should have done this from the start i know..
i am on MAc Big sur  ( is an old laptop but still gets security and safari updates thankfully)
safari version: Version 16.2 (16614.3.7.1.7, 16614)

**Comment by like-a-bause** [comment] 2023-01-17 14:38
Thanks for the info @gedw99
What Model is your Mac Book? Does it have a Secure Enclave?

**Comment by gedw99** [comment] 2023-01-17 14:39
MacBook Pro (Retina, 13-inch, Late 2013)

trying to find the that Secure enclave thing. seems with be the T2 chip ( aka tpm)
https://support.apple.com/en-us/HT208862

**Comment by gedw99** [comment] 2023-01-17 14:40
based on https://support.apple.com/en-us/HT208862 looks like i am way out of luck...

**Comment by FlxMgdnz** [comment] 2023-01-17 15:07
Good timing, though: https://www.apple.com/newsroom/2023/01/apple-unveils-macbook-pro-featuring-m2-pro-and-m2-max/

**Comment by gedw99** [comment] 2023-01-17 15:21
haha :) 

I have an oldie because i am a tight arse and it still works after 3 coffee spills. these old Mac laptop dinosaurs are freaking rocks 

but yeah its time to upgrade. 2 k !
"
The new 14-inch MacBook Pro with M2 Pro starts at $1,999 (US), and $1,849 (US) for education; and the 16-inch MacBook Pro with M2 Pro starts at $2,499 (US), and $2,299 (US) for education
"

**Comment by like-a-bause** [comment] 2023-01-17 16:00
That's right. I still have my late 2013 lying around. Maybe you can wait a couple of days an buy an M1 machine for less! These are beasts, too.
Glad we could figure out the cause. Closing for now.

**Closed by like-a-bause** 2023-01-17 16:00 UTC
Labels: bug
