### ISSUE TITLE
[🕹️]Technical article covering authentication, passkeys, etc. (300-1500 Points) 

### ISSUE THREAD

**Issue by AshishViradiya153** [teamhanko/hanko#1858] opened 2024-10-22 12:43 UTC
### What side quest or challenge are you solving?

Technical article covering authentication, passkeys, etc.

[medium article](https://medium.com/@ashishviradiya153/passkeys-the-future-of-authentication-and-passwordless-login-39a563ec793a)

### Points

?

### Provide proof that you've completed the task

article

**Comment by Khaan25** [comment] 2024-10-22 14:11
Seems like duplicate of my issue #1839

**Comment by AshishViradiya153** [comment] 2024-10-23 03:29
@Khaan25 double check everything, everyone can create blog ...

**Closed** 2024-10-31 16:47 UTC
Labels: hacktoberfest, 🕹️ oss.gg player submission
