### ISSUE TITLE
elements: headline wrap not styled properly

### ISSUE THREAD

**Issue by FlxMgdnz** [teamhanko/hanko#339] opened 2022-10-26 17:39 UTC
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

If headlines are wrapped, e.g. on smaller devices or when increasing the font size, the resulting style is not optimal:

![image](https://user-images.githubusercontent.com/20115649/198097013-b23e632e-25f9-424e-a382-547d6aac3cd0.png)

### Reproducing the bug

Visit e.g. passkeys.io on a device with less than 360px display width. This can easily be reproduced in Chrome dev tools.

### Hanko Version

0.2.0

**Comment by lfleischmann** [comment] 2022-10-26 17:42
What is version "0.2.1"? No tag exists for that version.

**Comment by FlxMgdnz** [comment] 2022-12-02 09:08
> What is Hanko Version "0.2.1"? No tag exists for that version.

Fixed

**Comment by bjoern-m** [comment] 2022-12-19 10:29
Can't reproduce, even with oversized headlines. Tried out 50px:

<img width="164" alt="Screenshot 2022-12-19 at 11 25 39" src="https://user-images.githubusercontent.com/56024829/208404442-d960db5c-35ae-419e-a7cd-f78b60037ad6.png">

And also it doesn't happen with 100px.

**Comment by FlxMgdnz** [comment] 2022-12-19 10:34
It happens with page zoom, e.g., 150%:

![image](https://user-images.githubusercontent.com/20115649/208406326-8a82bb81-7d7a-4a41-8c03-9cf8326192ff.png)

**Comment by bjoern-m** [comment] 2022-12-19 10:43
Seems like it happens on passkey.io because the body style has a line-height of 20px.

**Comment by bjoern-m** [comment] 2022-12-19 16:12
Created a PR, so the `line-height` is set and the headline should not inherit the property from another class.

**Comment by bjoern-m** [comment] 2023-01-25 15:57
Has been solved in https://github.com/teamhanko/hanko/pull/495, hence I close this issue.

**Closed by bjoern-m** 2023-01-25 15:57 UTC
Labels: bug
